### ISSUE TITLE
Durability Glitch

### ISSUE THREAD

**Issue by kamronalexander** [taggernation/ArmorSwap#1]
When right clicking to swap armor on player it auto fixes the armor and doesn't carry over the durability like it should. Error log placed below.

**Comment by kamronalexander** [comment]
`[23:21:06 FATAL]: Thread Netty Epoll Server IO #2 failed main thread check: Chunk getEntities call
java.lang.Throwable: null
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[patched_1.17.1.jar:git-Paper-"8d6a636"]
        at net.minecraft.server.level.ServerLevel.getEntities(ServerLevel.java:2322) ~[app:?]
        at net.minecraft.server.level.ServerLevel.getEntityOrPart(ServerLevel.java:1761) ~[app:?]
        at jdk.internal.reflect.GeneratedMethodAccessor77.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:16) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.EntityUtilities.getEntityFromID(EntityUtilities.java:234) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.getEntityFromID(PacketFilterManager.java:851) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.wrappers.BukkitConverters$11.getSpecific(BukkitConverters.java:721) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.wrappers.BukkitConverters$11.getSpecific(BukkitConverters.java:706) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:229) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:197) ~[ProtocolLib.jar:?]
        at com.reliableplugins.printer.hook.packets.ProtocolLibHook$1.onPacketReceiving(ProtocolLibHook.java:37) ~[Printer-3.1.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:537) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecieving(PacketFilterManager.java:509) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetReceived(ProtocolInjector.java:360) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:325) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:593) ~[ProtocolLib.jar:?]
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507) ~[patched_1.17.1.jar:git-Paper-"8d6a636"]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446) ~[patched_1.17.1.jar:git-Paper-"8d6a636"]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[patched_1.17.1.jar:git-Paper-"8d6a636"]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[patched_1.17.1.jar:git-Paper-"8d6a636"]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[patched_1.17.1.jar:git-Paper-"8d6a636"]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[patched_1.17.1.jar:git-Paper-"8d6a636"]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[patched_1.17.1.jar:git-Paper-"8d6a636"]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[patched_1.17.1.jar:git-Paper-"8d6a636"]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[patched_1.17.1.jar:git-Paper-"8d6a636"]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[patched_1.17.1.jar:git-Paper-"8d6a636"]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[patched_1.17.1.jar:git-Paper-"8d6a636"]
        at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:289) ~[ProtocolLib.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[patched_1.17.1.jar:git-Paper-"8d6a636"]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[patched_1.17.1.jar:git-Paper-"8d6a636"]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[patched_1.17.1.jar:git-Paper-"8d6a636"]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[patched_1.17.1.jar:git-Paper-"8d6a636"]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:311) ~[patched_1.17.1.jar:git-Paper-"8d6a636"]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:432) ~[patched_1.17.1.jar:git-Paper-"8d6a636"]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[patched_1.17.1.jar:git-Paper-"8d6a636"]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[patched_1.17.1.jar:git-Paper-"8d6a636"]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[patched_1.17.1.jar:git-Paper-"8d6a636"]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[patched_1.17.1.jar:git-Paper-"8d6a636"]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[patched_1.17.1.jar:git-Paper-"8d6a636"]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[patched_1.17.1.jar:git-Paper-"8d6a636"]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[patched_1.17.1.jar:git-Paper-"8d6a636"]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[patched_1.17.1.jar:git-Paper-"8d6a636"]
        at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152) ~[patched_1.17.1.jar:git-Paper-"8d6a636"]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[patched_1.17.1.jar:git-Paper-"8d6a636"]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[patched_1.17.1.jar:git-Paper-"8d6a636"]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[patched_1.17.1.jar:git-Paper-"8d6a636"]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[patched_1.17.1.jar:git-Paper-"8d6a636"]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[patched_1.17.1.jar:git-Paper-"8d6a636"]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[patched_1.17.1.jar:git-Paper-"8d6a636"]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[patched_1.17.1.jar:git-Paper-"8d6a636"]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795) ~[patched_1.17.1.jar:git-Paper-"8d6a636"]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480) ~[patched_1.17.1.jar:git-Paper-"8d6a636"]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[patched_1.17.1.jar:git-Paper-"8d6a636"]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[patched_1.17.1.jar:git-Paper-"8d6a636"]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[patched_1.17.1.jar:git-Paper-"8d6a636"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]`

**Comment by toonystank** [comment]
> When right clicking to swap armor on player it auto fixes the armor and doesn't carry over the durability like it should. Error log placed below.

I just tested the latest version on my server and there is no durability glitch. the durability carry over just fine. Do you have any plugin that alter armor equip ?


> `[23:21:06 FATAL]: Thread Netty Epoll Server IO #2 failed main thread check: Chunk getEntities call java.lang.Throwable: null at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[patched_1.17.1.jar:git-Paper-"8d6a636"] at net.minecraft.server.level.ServerLevel.getEntities(ServerLevel.java:2322) ~[app:?] at net.minecraft.server.level.ServerLevel.getEntityOrPart(ServerLevel.java:1761) ~[app:?] at jdk.internal.reflect.GeneratedMethodAccessor77.invoke(Unknown Source) ~[?:?] at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:16) ~[ProtocolLib.jar:?] at com.comphenix.protocol.injector.EntityUtilities.getEntityFromID(EntityUtilities.java:234) ~[ProtocolLib.jar:?] at com.comphenix.protocol.injector.PacketFilterManager.getEntityFromID(PacketFilterManager.java:851) ~[ProtocolLib.jar:?] at com.comphenix.protocol.wrappers.BukkitConverters$11.getSpecific(BukkitConverters.java:721) ~[ProtocolLib.jar:?] at com.comphenix.protocol.wrappers.BukkitConverters$11.getSpecific(BukkitConverters.java:706) ~[ProtocolLib.jar:?] at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:229) ~[ProtocolLib.jar:?] at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:197) ~[ProtocolLib.jar:?] at com.reliableplugins.printer.hook.packets.ProtocolLibHook$1.onPacketReceiving(ProtocolLibHook.java:37) ~[Printer-3.1.jar:?] at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114) ~[ProtocolLib.jar:?] at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67) ~[ProtocolLib.jar:?] at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:537) ~[ProtocolLib.jar:?] at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecieving(PacketFilterManager.java:509) ~[ProtocolLib.jar:?] at com.comphenix.protocol.injector.netty.ProtocolInjector.packetReceived(ProtocolInjector.java:360) ~[ProtocolLib.jar:?] at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:325) ~[ProtocolLib.jar:?] at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:593) ~[ProtocolLib.jar:?] at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507) ~[patched_1.17.1.jar:git-Paper-"8d6a636"] at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446) ~[patched_1.17.1.jar:git-Paper-"8d6a636"] at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[patched_1.17.1.jar:git-Paper-"8d6a636"] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[patched_1.17.1.jar:git-Paper-"8d6a636"] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[patched_1.17.1.jar:git-Paper-"8d6a636"] at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[patched_1.17.1.jar:git-Paper-"8d6a636"] at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[patched_1.17.1.jar:git-Paper-"8d6a636"] at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[patched_1.17.1.jar:git-Paper-"8d6a636"] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[patched_1.17.1.jar:git-Paper-"8d6a636"] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[patched_1.17.1.jar:git-Paper-"8d6a636"] at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[patched_1.17.1.jar:git-Paper-"8d6a636"] at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:289) ~[ProtocolLib.jar:?] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[patched_1.17.1.jar:git-Paper-"8d6a636"] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[patched_1.17.1.jar:git-Paper-"8d6a636"] at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[patched_1.17.1.jar:git-Paper-"8d6a636"] at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[patched_1.17.1.jar:git-Paper-"8d6a636"] at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:311) ~[patched_1.17.1.jar:git-Paper-"8d6a636"] at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:432) ~[patched_1.17.1.jar:git-Paper-"8d6a636"] at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[patched_1.17.1.jar:git-Paper-"8d6a636"] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[patched_1.17.1.jar:git-Paper-"8d6a636"] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[patched_1.17.1.jar:git-Paper-"8d6a636"] at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[patched_1.17.1.jar:git-Paper-"8d6a636"] at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[patched_1.17.1.jar:git-Paper-"8d6a636"] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[patched_1.17.1.jar:git-Paper-"8d6a636"] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[patched_1.17.1.jar:git-Paper-"8d6a636"] at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[patched_1.17.1.jar:git-Paper-"8d6a636"] at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152) ~[patched_1.17.1.jar:git-Paper-"8d6a636"] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[patched_1.17.1.jar:git-Paper-"8d6a636"] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[patched_1.17.1.jar:git-Paper-"8d6a636"] at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[patched_1.17.1.jar:git-Paper-"8d6a636"] at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[patched_1.17.1.jar:git-Paper-"8d6a636"] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[patched_1.17.1.jar:git-Paper-"8d6a636"] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[patched_1.17.1.jar:git-Paper-"8d6a636"] at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[patched_1.17.1.jar:git-Paper-"8d6a636"] at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795) ~[patched_1.17.1.jar:git-Paper-"8d6a636"] at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480) ~[patched_1.17.1.jar:git-Paper-"8d6a636"] at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[patched_1.17.1.jar:git-Paper-"8d6a636"] at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[patched_1.17.1.jar:git-Paper-"8d6a636"] at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[patched_1.17.1.jar:git-Paper-"8d6a636"] at java.lang.Thread.run(Thread.java:833) ~[?:?]`

This issue is not related to armorswap plugin

**Comment by toonystank** [comment]
> `[23:21:06 FATAL]: Thread Netty Epoll Server IO #2 failed main thread check: Chunk getEntities call java.lang.Throwable: null at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[patched_1.17.1.jar:git-Paper-"8d6a636"] at net.minecraft.server.level.ServerLevel.getEntities(ServerLevel.java:2322) ~[app:?] at net.minecraft.server.level.ServerLevel.getEntityOrPart(ServerLevel.java:1761) ~[app:?] at jdk.internal.reflect.GeneratedMethodAccessor77.invoke(Unknown Source) ~[?:?] at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:16) ~[ProtocolLib.jar:?] at com.comphenix.protocol.injector.EntityUtilities.getEntityFromID(EntityUtilities.java:234) ~[ProtocolLib.jar:?] at com.comphenix.protocol.injector.PacketFilterManager.getEntityFromID(PacketFilterManager.java:851) ~[ProtocolLib.jar:?] at com.comphenix.protocol.wrappers.BukkitConverters$11.getSpecific(BukkitConverters.java:721) ~[ProtocolLib.jar:?] at com.comphenix.protocol.wrappers.BukkitConverters$11.getSpecific(BukkitConverters.java:706) ~[ProtocolLib.jar:?] at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:229) ~[ProtocolLib.jar:?] at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:197) ~[ProtocolLib.jar:?] at com.reliableplugins.printer.hook.packets.ProtocolLibHook$1.onPacketReceiving(ProtocolLibHook.java:37) ~[Printer-3.1.jar:?] at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114) ~[ProtocolLib.jar:?] at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67) ~[ProtocolLib.jar:?] at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:537) ~[ProtocolLib.jar:?] at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecieving(PacketFilterManager.java:509) ~[ProtocolLib.jar:?] at com.comphenix.protocol.injector.netty.ProtocolInjector.packetReceived(ProtocolInjector.java:360) ~[ProtocolLib.jar:?] at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:325) ~[ProtocolLib.jar:?] at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:593) ~[ProtocolLib.jar:?] at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507) ~[patched_1.17.1.jar:git-Paper-"8d6a636"] at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446) ~[patched_1.17.1.jar:git-Paper-"8d6a636"] at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[patched_1.17.1.jar:git-Paper-"8d6a636"] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[patched_1.17.1.jar:git-Paper-"8d6a636"] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[patched_1.17.1.jar:git-Paper-"8d6a636"] at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[patched_1.17.1.jar:git-Paper-"8d6a636"] at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[patched_1.17.1.jar:git-Paper-"8d6a636"] at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[patched_1.17.1.jar:git-Paper-"8d6a636"] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[patched_1.17.1.jar:git-Paper-"8d6a636"] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[patched_1.17.1.jar:git-Paper-"8d6a636"] at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[patched_1.17.1.jar:git-Paper-"8d6a636"] at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:289) ~[ProtocolLib.jar:?] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[patched_1.17.1.jar:git-Paper-"8d6a636"] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[patched_1.17.1.jar:git-Paper-"8d6a636"] at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[patched_1.17.1.jar:git-Paper-"8d6a636"] at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[patched_1.17.1.jar:git-Paper-"8d6a636"] at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:311) ~[patched_1.17.1.jar:git-Paper-"8d6a636"] at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:432) ~[patched_1.17.1.jar:git-Paper-"8d6a636"] at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[patched_1.17.1.jar:git-Paper-"8d6a636"] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[patched_1.17.1.jar:git-Paper-"8d6a636"] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[patched_1.17.1.jar:git-Paper-"8d6a636"] at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[patched_1.17.1.jar:git-Paper-"8d6a636"] at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[patched_1.17.1.jar:git-Paper-"8d6a636"] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[patched_1.17.1.jar:git-Paper-"8d6a636"] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[patched_1.17.1.jar:git-Paper-"8d6a636"] at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[patched_1.17.1.jar:git-Paper-"8d6a636"] at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152) ~[patched_1.17.1.jar:git-Paper-"8d6a636"] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[patched_1.17.1.jar:git-Paper-"8d6a636"] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[patched_1.17.1.jar:git-Paper-"8d6a636"] at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[patched_1.17.1.jar:git-Paper-"8d6a636"] at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[patched_1.17.1.jar:git-Paper-"8d6a636"] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[patched_1.17.1.jar:git-Paper-"8d6a636"] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[patched_1.17.1.jar:git-Paper-"8d6a636"] at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[patched_1.17.1.jar:git-Paper-"8d6a636"] at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795) ~[patched_1.17.1.jar:git-Paper-"8d6a636"] at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480) ~[patched_1.17.1.jar:git-Paper-"8d6a636"] at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[patched_1.17.1.jar:git-Paper-"8d6a636"] at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[patched_1.17.1.jar:git-Paper-"8d6a636"] at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[patched_1.17.1.jar:git-Paper-"8d6a636"] at java.lang.Thread.run(Thread.java:833) ~[?:?]`

This issue is seems to be coming from a plugin called "Printer"
